### ISSUE TITLE
sbt doesn't start after fudging Ivy cache manually

### ISSUE THREAD

**Issue by salakta** [sbt/sbt-launcher-package#109]
Hi,
I insatalled sbt as described , but i got this issues:

```
getting Scala 2.10.6 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
	confs: [default]
	5 artifacts copied, 0 already retrieved (24392kB/59ms)
java.lang.NoClassDefFoundError: jline/TerminalFactory
	at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:123)
	at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:117)
	at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
	at sbt.GlobalLogging$.initial(GlobalLogging.scala:43)
	at sbt.StandardMain$.initialGlobalLogging(Main.scala:61)
	at sbt.StandardMain$.initialState(Main.scala:70)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: jline.TerminalFactory
```

Please help.
Regards,

**Comment by eed3si9n** [comment]
Could you describe exactly what you did, and what environment you have?
There are many ways of installing sbt, and if one of the sbt developers cannot reproduce your problem, it's difficult to help. One thing you could try is wiping out `~/.sbt/boot` directory if you have one.

**Comment by salakta** [comment]
i just wanted to install sbt, so i downloded the last version and launched sbt (unzip and launch ./bin/sbt) 
At first i have problems with jline and Jansi librairies (it canot be downloaded due to network issues), do i downloaded these libraries manually and added them to ~/.ivy/cache/{library}
i tried to delete ~/.sbt/boot, but it not helps

**Comment by eed3si9n** [comment]
> At first i have problems with jline and Jansi librairies (it canot be downloaded due to network issues), do i downloaded these libraries manually and added them to ~/.ivy/cache/{library}

ok. Messing with Ivy cache manually is a bad idea. Definitely not part of sbt installation step.
