### ISSUE TITLE
Travis CI breaking

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-launcher-package#180]
Travis CI build errors on current.

**Comment by dwijnand** [comment]
https://travis-ci.org/sbt/sbt-launcher-package

Error from https://travis-ci.org/sbt/sbt-launcher-package/builds/271083862:

```
java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
	at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:64)
	at scala.collection.IterableLike$class.head(IterableLike.scala:91)
	at scala.collection.mutable.ArrayBuffer.scala$collection$IndexedSeqOptimized$$super$head(ArrayBuffer.scala:47)
	at scala.collection.IndexedSeqOptimized$class.head(IndexedSeqOptimized.scala:120)
	at scala.collection.mutable.ArrayBuffer.head(ArrayBuffer.scala:47)
	at $b13f1b640bc9a920bfed$$anonfun$dist$10.apply(build.sbt:323)
	at $b13f1b640bc9a920bfed$$anonfun$dist$10.apply(build.sbt:318)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (dist/*:exportRepo) java.util.NoSuchElementException: next on empty iterator
[error] Total time: 25 s, completed Sep 2, 2017 5:12:12 AM
restoring stty: 500:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
The command "sbt -Dsbt.build.version=1.0.0-M1 ++$TRAVIS_SCALA_VERSION rpm:packageBin debian:packageBin universal:packageBin" exited with 1.
```
